### ISSUE TITLE
Non-working features (so far checked) - tested setup.exe

### ISSUE THREAD

**Issue by Saphircelestial** [franciscoBSalgueiro/en-croissant#10]
Promote variation
Delete variation

File deletion works as long as the "Virus & threat protection -> Ransomware protection -> Controlled folder access" is turned off.

v0.5.0

**Comment by franciscoBSalgueiro** [comment]
Thanks for the feedback! Could you provide an example where promote and delete variations don't work?

**Comment by Saphircelestial** [comment]
It does just not work actually. Like I try to delete the variation, but it just does not take any action at all.

**Comment by Saphircelestial** [comment]
Ruy Lopez in the edit position is actually an Italian

**Comment by franciscoBSalgueiro** [comment]
> It does just not work actually. Like I try to delete the variation or promote it, but it just does not take any action at all.

That's strange, it seems to work correctly for me.

> Ruy Lopez in the edit position is actually an Italian

Yes, thank you. I wanted to have a full list of openings searchable in that list but forgot about it.

**Comment by Saphircelestial** [comment]
Well, in my case it actually does not do a thing. Are you sure you are using v0.5.0 by any chance?

**Comment by Saphircelestial** [comment]
Actually it works if I'll just use arrows + enter

**Comment by franciscoBSalgueiro** [comment]
Yes, I'm using 0.5.0.

> Actually it works if I'll just do left click + guide with arrows keys then click enter

How were you doing it before? I can't reproduce it.

**Comment by Saphircelestial** [comment]
well, I left click on the move, then use arrows keys to navigate and click enter :)
