### ISSUE TITLE
Adding Score above Eval bar on the left in the analysis board.

### ISSUE THREAD

**Issue by Tyler-Jay-Stevahn** [franciscoBSalgueiro/en-croissant#100]
Great program, I found some issues with regular moves being regarded as illegal moves. But I haven't been able to replicate those.

Would it be possible to have the current evaluation be above the evaluation bar that is on the left of the board in analysis board tab? The score is already present if you hover over the bar, but an option to leave it showing just above the bar would be great. 

Thanks

**Comment by franciscoBSalgueiro** [comment]
That's a good idea, I've added a label similar to the one in chess.com

**Comment by Tyler-Jay-Stevahn** [comment]
Glad I can help 👍, thanks for implementing it so quickly.
