### ISSUE TITLE
Can we avoid using xdg-data-dirs in main.rs?

### ISSUE THREAD

**Issue by Animeshz** [franciscoBSalgueiro/en-croissant#118]
### Describe the bug

Originating from https://github.com/franciscoBSalgueiro/en-croissant/blob/v0.7.1/src-tauri/src/main.rs#L82

```bash
thread 'main' panicked at src/main.rs:181:18:
called `Result::unwrap()` on an `Err` value: Path("unable to determine base dir path")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Reproduction

Happens when user doesn't have xdg-data-dirs package installed. `resolve_path()` on `(BaseDirectory::Document, "EnCroissant"),` is only possible in linux when xdg-data-dirs is installed and set to be used. Which is generally not always the case, specially when we're not using 100% xdg complaint systems.

Can we try to avoid using user's Document directory for creating files?

Also, it took me few tries to find the culprit, can we also improve the error messages (avoid using `unwrap()` and maybe atleast `expect()` to give more useful information)?

Thanks!

### Platform and versions

OS: Void Linux (base) - glibc latest

**Comment by franciscoBSalgueiro** [comment]
Thanks, I try to minimize the amount of unwraps, but I'm also often lazy.
