### ISSUE TITLE
Analysis engine issues

### ISSUE THREAD

**Issue by 12345z** [franciscoBSalgueiro/en-croissant#121]
### Describe the bug

If this issue already exists and is is known please excuse me. 

I have observed the following two problems with analysis:
1. When stockfish analysis is running and i skip forward a couple moves very fast (holding down the arrow keys) stockfish seems to get stuck (doesnt show evaluation but is still eating up CPU and RAM). I attached a screenshot for this issue:

![Screenshot 2024-01-14 181311](https://github.com/franciscoBSalgueiro/en-croissant/assets/1223786/c08fd823-fed9-4e0a-947c-80391f31b112)

2. Stockfish keeps running very often even after pausing analysis, closing the tab with ctrl+w and then closing the app. EnCroissant and the subprocess stockfish is still running in the background and again eating up system ressources.

Hope that description helps! And again sorry if these are already known issues.

### Reproduction

1. Got to analysis
2. Insert PGN
3. Start stockfish
4. Skip forward a couple of moves fast by holding down "right arrow" key

### Platform and versions

OS: Windows 10
EnCroissant: Built latest version from sources

**Comment by franciscoBSalgueiro** [comment]
I believe https://github.com/franciscoBSalgueiro/en-croissant/commit/ee863eee8d6e9e12bd8de53b4f1277a56161cdcf should fix this issue. Please let me know if it persists.
