### ISSUE TITLE
freeze on startup

### ISSUE THREAD

**Issue by RtWlu3** [franciscoBSalgueiro/en-croissant#123]
### Describe the bug

I don't really know what happened all i know is that when i downloaded this software it froze on startup and any attempts made by me to not get it to freeze have failed. all it says is that it isnt responding

### Reproduction

download
start the program

### Platform and versions

windows 10 64 bit

**Comment by franciscoBSalgueiro** [comment]
I'm unable to reproduce. Is there anything written to the logs? They should be located on `%AppData%\org.encroissant.app\logs`

**Comment by RtWlu3** [comment]
uh it works now, im not sure why but i added a chess.com account but heres the logs anyways
[en-croissant.log](https://github.com/franciscoBSalgueiro/en-croissant/files/13998273/en-croissant.log)

**Comment by ExpeditionEchecs** [comment]
> uh it works now, im not sure why but i added a chess.com account but heres the logs anyways [en-croissant.log](https://github.com/franciscoBSalgueiro/en-croissant/files/13998273/en-croissant.log)

I'm getting the same warnings in my log, just downloaded the app and unable to do anything with it.

**Comment by franciscoBSalgueiro** [comment]
I'm adding better logging but I still have no clue as to what the issue might be.

**Comment by shaunkahler** [comment]
Same issue here.

**Comment by franciscoBSalgueiro** [comment]
> Same issue here. Unable to locate logs in specified folder, please advise.

That's very strange. The folder exists, but there's no file? That file is created on startup so if it opens it should exist.

**Comment by shaunkahler** [comment]
There is no folder in that location.

**Comment by franciscoBSalgueiro** [comment]
Could you try to run the dev version to see if there's anything else we can find?

You'll need to have rust and node installed, and then run these after cloning:

`pnpm install`
`pnpm tauri dev`

**Comment by shaunkahler** [comment]
Can do.

Keep in mind these kinds of bugs should (never) exist open within executables O.o

**Comment by shaunkahler** [comment]
In addition. Can you please provide the correct location for the logs folder.

**Comment by franciscoBSalgueiro** [comment]
> In addition. Can you please provide the correct location for the logs folder.

The correct location is, as said above, in `%AppData%\org.encroissant.app\logs`. `%AppData%` is the windows shortened version for `C:\Users\<your username>\AppData/Roaming`. I've only now seen your screenshots, where you opened `AppData/Local`  which would be `%LocalAppData%`.

**Comment by shaunkahler** [comment]
Got it, and thanks for the clarification.

Here's the log, I don't see much. Freezing happens after load, once I click on (pretty much anything), whether that's one of the menus at the top, or the add button. End result is unresponsive application.

[2024-02-10][18:29:58][INFO][en_croissant] Setting up application
[2024-02-10][18:29:58][INFO][en_croissant] Checking for required directories
[2024-02-10][18:29:58][INFO][en_croissant] Creating directory C:\Users\shaun\AppData\Roaming\org.encroissant.app\engines
[2024-02-10][18:29:58][INFO][en_croissant] Creating directory C:\Users\shaun\AppData\Roaming\org.encroissant.app\db
[2024-02-10][18:29:58][INFO][en_croissant] Creating directory C:\Users\shaun\AppData\Roaming\org.encroissant.app\presets
[2024-02-10][18:29:58][INFO][en_croissant] Creating directory C:\Users\shaun\AppData\Roaming\org.encroissant.app\puzzles
[2024-02-10][18:29:58][INFO][en_croissant] Creating directory C:\Users\shaun\AppData\Roaming\org.encroissant.app\documents
[2024-02-10][18:29:58][INFO][en_croissant] Creating directory C:\Users\shaun\OneDrive\Cloud Storage\EnCroissant
[2024-02-10][18:29:58][INFO][en_croissant] Checking for required files
[2024-02-10][18:29:58][INFO][en_croissant] Creating file C:\Users\shaun\AppData\Roaming\org.encroissant.app\engines/engines.json
[2024-02-10][18:30:24][INFO][en_croissant] Setting up application
[2024-02-10][18:30:24][INFO][en_croissant] Checking for required directories
[2024-02-10][18:30:24][INFO][en_croissant] Checking for required files
[2024-02-10][18:31:10][INFO][en_croissant] Setting up application
[2024-02-10][18:31:10][INFO][en_croissant] Checking for required directories
[2024-02-10][18:31:10][INFO][en_croissant] Checking for required files
[2024-02-10][18:33:35][INFO][en_croissant] Setting up application
[2024-02-10][18:33:35][INFO][en_croissant] Checking for required directories
[2024-02-10][18:33:35][INFO][en_croissant] Checking for required files
[2024-02-10][20:16:07][INFO][en_croissant] Setting up application
[2024-02-10][20:16:07][INFO][en_croissant] Checking for required directories
[2024-02-10][20:16:07][INFO][en_croissant] Checking for required files

**Comment by shaunkahler** [comment]
I'll see if I can reproduce via build and follow up.

**Comment by franciscoBSalgueiro** [comment]
Are there any errors or warnings in the console (it can be opened with f12 in the dev version)? Is the app showing any CPU usage before the freeze?

**Comment by shaunkahler** [comment]
In dev version, I can't get as far as opening the console. The app does show some CPU usage before the window opens.

**Comment by franciscoBSalgueiro** [comment]
I've made a branch with a stripped down version of the home page. Can you check if this also freezes?

https://github.com/franciscoBSalgueiro/en-croissant/tree/freeze-fix-1

**Comment by shaunkahler** [comment]
No freezing for the new branch (observing "this is a test"), here is log:

![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/147385418/d6ee27ca-d796-409f-983b-6111f5439846)

**Comment by shaunkahler** [comment]
Can't see any chess pieces in this branch though.

**Comment by franciscoBSalgueiro** [comment]
I've made the boards page the new initial page (on the master branch). Can you check if it still freezes?

**Comment by shaunkahler** [comment]
Still freezing. 
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/147385418/cfde0fdf-856c-4d97-afd1-411e6c793142)

**Comment by franciscoBSalgueiro** [comment]
Ok, so that really narrows down the problem to one file: `App.tsx`

**Comment by franciscoBSalgueiro** [comment]
https://github.com/franciscoBSalgueiro/en-croissant/tree/freeze-fix-2
https://github.com/franciscoBSalgueiro/en-croissant/tree/freeze-fix-2
https://github.com/franciscoBSalgueiro/en-croissant/tree/freeze-fix-2

**Comment by shaunkahler** [comment]
These all freeze

![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/147385418/c8843cdc-575f-4cda-961b-22264a746408)

**Comment by franciscoBSalgueiro** [comment]
Does this one help?

 https://github.com/franciscoBSalgueiro/en-croissant/tree/freeze-fix-7

**Comment by shaunkahler** [comment]
Freezes

**Comment by shaunkahler** [comment]
Is there anything I can do from my end to determine where the app is crashing in VS Code?

**Comment by franciscoBSalgueiro** [comment]
Maybe try changing the "visible" and "decoration" settings on tauri.conf.json

**Comment by shaunkahler** [comment]
Looks like I can uncomment everything on App.tsx up to line 241-247 without crashes. I would uncomment this part but am unsure of the syntax and get errors when I attempt:

`      {/* <AboutModal opened={opened} setOpened={setOpened} /> }
      {/* {!isNative && (
        <AppShell.Header>
          <TopBar menuActions={menuActions} />
        </AppShell.Header>
      )} */}`

**Comment by franciscoBSalgueiro** [comment]
The changes to tauri.conf.json I mentioned didn't have any result?

That part uncommented would become this:

<AboutModal opened={opened} setOpened={setOpened} />
{!isNative && ( <AppShell.Header> <TopBar menuActions={menuActions} /> </AppShell.Header> )}

Also, it might be worth to restart after changing. After uncommenting everything the result is the same as the master branch so at some point it has to freeze again.

**Comment by shaunkahler** [comment]
Changing decorations to false does crash it.

**Comment by franciscoBSalgueiro** [comment]
Ok great, so even in the master branch, if you change decorations to true it'll not freeze, right?

**Comment by shaunkahler** [comment]
Correct, just tested this.

**Comment by franciscoBSalgueiro** [comment]
Thank you very much for your help!

One more thing, does the combination of `maximized: false` and `decorations: false` work as well?

**Comment by franciscoBSalgueiro** [comment]
https://github.com/franciscoBSalgueiro/en-croissant/commit/9955fa3d8c2ef1496d10e037b93a1d2606ce038a has fixed the issue for me. Can you confirm it now works as intended @shaunkahler?

**Comment by shaunkahler** [comment]
Can confirm, able to change these windows settings without crash.

**Comment by franciscoBSalgueiro** [comment]
Great! thanks again for the help
