### ISSUE TITLE
Support for multiple engines at once (for Analysis)

### ISSUE THREAD

**Issue by Coccocoahelper** [franciscoBSalgueiro/en-croissant#129]
### Describe the feature

This makes it possible to find bad habits in playstyle, and many, MANY other things.

**Comment by dav1312** [comment]
You can already enable multiple engines at once in the analysis board.
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/63931154/82abcd81-f180-444a-956c-26acbce84585)
