### ISSUE TITLE
Automatically detect available engine settings

### ISSUE THREAD

**Issue by franciscoBSalgueiro** [franciscoBSalgueiro/en-croissant#132]
> The uci command also outputs all the available options with their type, and their default values. Sending the engine options that it doesn't support may cause unexpected issues.
Something that would be cool is adding a button to select a file from the computer if the option has "file" (or "File") in its name.

I think you're describing the BanksiaGUI engine settings menu, right @dav1312?. This would be a nice improvement.

![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/92053465/b50c7bf5-0f7d-4823-81e8-f022a9c1fe39)

**Comment by dav1312** [comment]
Not just Banksia but yeah
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/63931154/7dd24fed-c191-4e01-9343-894157367edb)
