### ISSUE TITLE
JSON Parse error: Unexpected EOF

### ISSUE THREAD

**Issue by N1ghtey** [franciscoBSalgueiro/en-croissant#134]
### Describe the bug

parse@[native code] @tauri://localhost/assets/index.js:244:10017 @[native code]

### Reproduction

1. Entering Engines tab shows such output, not possible to add any engine in. Reloading does not help.

### Platform and versions

v0.8.0-beta amd64.AppImage
OS: Arch Linux x86_64
Kernel: 6.7.2-arch1-1
DE: Plasma 5.27.10

**Comment by franciscoBSalgueiro** [comment]
Can you check if you still have the same error on the newest version? I've just merged a large PR related to engine settings. https://github.com/franciscoBSalgueiro/en-croissant/pull/138

**Comment by N1ghtey** [comment]
Came back to normal, working fine.

**Comment by N1ghtey** [comment]
The new design is good, keep the good work!

**Comment by N1ghtey** [comment]
Though, I found that Lichess cloud after 1. e4 (Multipv2) shows 1... cxc6 instead 1... c6 lol

**Comment by franciscoBSalgueiro** [comment]
Thanks, it's fixed now
