### ISSUE TITLE
Show preview of piece sets

### ISSUE THREAD

**Issue by Azmisov** [franciscoBSalgueiro/en-croissant#137]
### Describe the feature

You need to keep going back and forth between board and settings to view what the pieces look like. Workaround is to go look at the piece sets on lichess.org and then check the name of the one you like.

**Comment by dav1312** [comment]
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/63931154/5e346dc0-2b84-4dc7-bd21-73a1801416e5)
this was already implemented
