### ISSUE TITLE
No issue! Just want to say thanks! Also, happy to help!

### ISSUE THREAD

**Issue by neuromaancer** [franciscoBSalgueiro/en-croissant#140]
### Describe the feature

I am so happy to have found this open-source app! And also happy is in a French name 😄!
Willing to help. And suggest opening the discussion section for non-issue discussion.

**Comment by franciscoBSalgueiro** [comment]
I'm glad you like it! I'm always open to ideas or pull requests if you want to help.

I've enabled discussions now.
