### ISSUE TITLE
Remember the sizes of window elements

### ISSUE THREAD

**Issue by franciscoBSalgueiro** [franciscoBSalgueiro/en-croissant#146]
fixed by 089e8ffdce05c656677ee4cd6d05d262311e5eac

**Comment by dav1312** [comment]
Would it be possible to remember them even after the app is closed?

**Comment by franciscoBSalgueiro** [comment]
They should be now. Before they were already remembered while the app was open.

**Comment by dav1312** [comment]
It doesn't seem to work for me. Maybe we are just misunderstanding each other.
If I change the elements to look like this
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/63931154/2dab9d84-133e-415b-bf4e-21d653eccbe8)

When I reopen the app they have their default size
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/63931154/aa7c9eb5-69bb-46d3-aee5-1c979d5d0b32)
