### ISSUE TITLE
Analysis board crashes

### ISSUE THREAD

**Issue by Disservin** [franciscoBSalgueiro/en-croissant#147]
### Describe the bug

Opening the analysis board crashes.

### Reproduction

After running `npm run tauri dev` and then navigating to `Board` and then `Open Analysis Board` leads to the following crash.

### Platform and versions

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic

### Stack trace

```Shell
JSON Parse error: Unexpected EOF
parse@[native code]
@http://localhost:1420/src/atoms/utils.ts:48:52
```
```

**Comment by franciscoBSalgueiro** [comment]
Thanks! It should be fixed now
