### ISSUE TITLE
Change board colors

### ISSUE THREAD

**Issue by dxkill** [franciscoBSalgueiro/en-croissant#150]
### Describe the feature

It would be really cool if you could change the board colors to either any rgb color or preset palettes.

**Comment by ThatChapThere** [comment]
This feels like an essential feature for a chess program, I agree.

**Comment by mattbruv** [comment]
Thirded

**Comment by pure-blue** [comment]
Just came here to make the same request. I'm a dark mode slut and the board is really quite bright. 

LOVE this app, great job and thank you.
