### ISSUE TITLE
Adding Pieces to Board Editor

### ISSUE THREAD

**Issue by cFlour** [franciscoBSalgueiro/en-croissant#154]
### Describe the bug

Not able to add pieces to the Board Editor

### Reproduction

1. Go to the analysis board.
2. Click Edit the board.
3. Remove all the pieces.
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/79126652/9a7d5d9a-519b-4862-9867-3cdb0f5dc837)

### Platform and versions

Windows 11
Version is the latest one available for download on [the website](https://encroissant.org/).

**Comment by dav1312** [comment]
pull the window up, the pieces are below the castling rights

![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/63931154/76f1156a-1292-49e3-8f8b-2c93b2823c47)

**Comment by franciscoBSalgueiro** [comment]
Just to clarify, you can resize each panel by dragging this purple line

![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/92053465/4503e89c-5026-4a57-aaf7-d64d3a6367c3)
