### ISSUE TITLE
Engine Error: Illegal UCI, when king enters the corner

### ISSUE THREAD

**Issue by Alex2262** [franciscoBSalgueiro/en-croissant#167]
### Describe the bug

When any king enters the square H1, H8, A1 or A8, the popup of "Error: Illegal UCI" is encountered while using the built-in Stockfish binary and the engine Altair. Stockfish is then unable to analyze the position once a king enters one of these squares.

### Reproduction

1. Open up an analysis board.
2. Begin analysis with the stockfish engine (any other engine may reproduce the issue)
3. Move the king to one of the corner squares, example game:

1. e4 e5 2. Nf3 Nf6 3. Bc4 Bc5 4. O-O O-O 5. Kh1

Kh1 produces the error.

### Platform and versions

The program is being run on my Mac M1 with version 0.9.1 of En Croissant.

**Comment by franciscoBSalgueiro** [comment]
This was fixed by https://github.com/franciscoBSalgueiro/en-croissant/commit/1a267dc687b939ab46cdec139a2c0a6607139eed
