### ISSUE TITLE
feat: show directories alongside files

### ISSUE THREAD

**Issue by latenitecoding** [franciscoBSalgueiro/en-croissant#168]
### Describe the feature

There doesn't currently seem to be a way to navigate through directories in the files tab. I like to organize games into different folders. I would like to see those folders in the files tab and be able to navigate through them to find my chess games.

**Comment by franciscoBSalgueiro** [comment]
This was added in https://github.com/franciscoBSalgueiro/en-croissant/commit/fa1ae804542efa48ebf97f6a95b36d0554faa0ad. There isn't a way to add folders in-app, but if you create them they will show up.
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/92053465/a113f3fa-00f3-431e-8ef3-194e75b28c56)
