### ISSUE TITLE
TypeError: undefined is not an object (evaluating 't[r-1].best[0].score')

### ISSUE THREAD

**Issue by adam-ehab-code** [franciscoBSalgueiro/en-croissant#173]
### Describe the bug

The error happens when trying to Report some games .. It happens today .. When I tried to report games the past week it was reported successfully but today .. I always get this error 

### Reproduction

1. I Open any game from my [ chess.com profile ] database and then from analysis section ... choose report game and start the report and after sometimes .. this error appears 

### Platform and versions

OS : Linux / Debian 

### Stack trace

```Shell
undefined is not an object (evaluating 't[r-1].best[0].score')
Y5e@tauri://localhost/assets/index.js:143:4642
@tauri://localhost/assets/index.js:143:2168
with@tauri://localhost/assets/index.js:43:8119
bJ@tauri://localhost/assets/index.js:143:2115
@tauri://localhost/assets/index.js:243:900537
ax@tauri://localhost/assets/index.js:38:20836
kk@tauri://localhost/assets/index.js:243:902596
AT@tauri://localhost/assets/index.js:38:19553
Lz@tauri://localhost/assets/index.js:40:3145
oZ@tauri://localhost/assets/index.js:40:39824
xfe@tauri://localhost/assets/index.js:40:39750
ag@tauri://localhost/assets/index.js:40:39601
Zz@tauri://localhost/assets/index.js:40:35962
rZ@tauri://localhost/assets/index.js:40:34909
rZ@[native code]
z@tauri://localhost/assets/index.js:25:1541
R@tauri://localhost/assets/index.js:25:1900
```

**Comment by franciscoBSalgueiro** [comment]
This has already been fixed. You can use the [pre-release](https://github.com/franciscoBSalgueiro/en-croissant/releases/tag/master-beta) version or wait for the next patch.
