### ISSUE TITLE
No Admin Installation / Running

### ISSUE THREAD

**Issue by q6276270** [franciscoBSalgueiro/en-croissant#175]
I just had a cursory glance at en croissant and thus far it looks great, like a lot of things I have been looking for, for quite some time. Thanks for the effort!

Just a suggestion: I do develop software myself though not gui-based apps but I feel if at all possible such a program should not require admin privileges to install or run. Actually ideally it should be standalone.

What do you think?

**Comment by franciscoBSalgueiro** [comment]
This has been suggested here as well https://github.com/franciscoBSalgueiro/en-croissant/issues/165. I would like to do it, but there's no option for standalone executables in the github action used to make the releases.
