### ISSUE TITLE
Puzzles are broken

### ISSUE THREAD

**Issue by ThatChapThere** [franciscoBSalgueiro/en-croissant#177]
### Describe the bug

When you try to solve a puzzle with more than one move, if you make the correct move nothing happens and the move is reversed, not even showing on the move list. Making an incorrect move still behaves as intended, marking the puzzle as failed. One move puzzles correctly mark themselves as correct on solving.

Do this:

![Screenshot 2024-02-13 183826](https://github.com/franciscoBSalgueiro/en-croissant/assets/19906834/5f61f954-0075-4b3c-956b-b4c8e2e97b9e)

And you'll just see this afterwards:

![Screenshot 2024-02-13 183838](https://github.com/franciscoBSalgueiro/en-croissant/assets/19906834/b4248b87-0420-4261-aa04-7d62a9ed6a2d)

### Reproduction

Attempt to solve a puzzle with more than one move in the solution.

### Platform and versions

Version: 0.9.1

Tauri version: 1.5.2

OS: Windows_NT x86_64 10.0.22631

**Comment by franciscoBSalgueiro** [comment]
This has already been fixed. You can use the [pre-release](https://github.com/franciscoBSalgueiro/en-croissant/releases/tag/master-beta) version or wait for the next patch.
