### ISSUE TITLE
Unable to Analyze games with Lc0 and lichess cloud for all games

### ISSUE THREAD

**Issue by qqiumax** [franciscoBSalgueiro/en-croissant#180]
### Describe the bug

For Lc0, it had a hard time starting up and failed to analyze for all games, and for lichess cloud, only a few moves are possible until it says "no analysis possible"
![Uploading image.png…]()
Also, a report is unable to be generated as Lc0 is not working and the rest of the engines cannot be downloaded for me, see another issue for this

### Reproduction

1. Go to my database
2. Views the game
3. Start analysis, engines
4. opened Microsoft edge
5. Came back after 3 seconds
6. Failed to start

### Platform and versions

Windows 10, using Lc0 30.0.0, newest version of en croissant

**Comment by qqiumax** [comment]
The image and logs are provided here
[logs.csv](https://github.com/franciscoBSalgueiro/en-croissant/files/14274908/logs.csv)
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/102963434/0fcd43c6-16a8-4874-8e3c-e3d6312400c4)

**Comment by franciscoBSalgueiro** [comment]
In the logs there's this: `error No CUDA driver`
En Croissant downloads the fastest version by default but if your hardware doesn't support it you'll need to download a different manually. You can see the requirements [here](https://lczero.org/play/download/).
