### ISSUE TITLE
Unable to download Stockfish16 and Komodo 14

### ISSUE THREAD

**Issue by qqiumax** [franciscoBSalgueiro/en-croissant#181]
### Describe the bug

![Uploading image.png…]()

### Reproduction

1. Go to engines, add new engine
2. Click install
3. Bug appears

### Platform and versions

Windows 10

**Comment by qqiumax** [comment]
image here
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/102963434/380cdc5c-b005-4ab0-a12c-fec5f784e503)

**Comment by F0r9e** [comment]
这是国内连接github慢的问题吧，貌似跟软件没关系

**Comment by franciscoBSalgueiro** [comment]
I don't think this is related to En Croissant. Check if you can download it manually:
https://github.com/official-stockfish/Stockfish/releases/download/sf_16/stockfish-windows-x86-64-avx2.zip
