### ISSUE TITLE
Some features

### ISSUE THREAD

**Issue by F0r9e** [franciscoBSalgueiro/en-croissant#183]
### Describe the feature

A few feature suggestions that may be helpful.

#### Play
- [ ] - Start the game clock after both players make a move
- [ ] - An option to flip the board automatically
- [ ] - Show player name next to the clock
- [ ] - Resign or end game button

#### Analysis
- [ ] - Make the "Edit Position" into a single feature on the new tab, allowing the position created to be played, analyzed, and saved
- [ ] - Generating multiple reports from different tabs at the same time
- [ ] - Show player ELO next to the clock
- [ ] - Show game termination (if provided)
- [ ] - An option to use cloud eval when generating a report
- [ ] - Save engine analysis settings 
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/61375029/7dba5c5a-1667-4c72-9ccd-9a09a9fa0c07)

#### Accounts
- [ ] - Switch overviews when clicking on different accounts
- [ ] - A link to the account profile
- [ ] - Change the order of different accounts

**Comment by dxkill** [comment]
Yeah those make sense, especially the saving of analysis settings.
