### ISSUE TITLE
Allow viewing local DB game match results filtered by a player and color 

### ISSUE THREAD

**Issue by mattbruv** [franciscoBSalgueiro/en-croissant#189]
### Describe the feature

It seems to me like if this change is implemented, En-croissant would just completely replace the need for using [OpeningTree](https://www.openingtree.com/). 

Right now when you look at a local database, The results percentage is calculated by total white wins, regardless of who was playing white. 

If you added the ability to  say: "I want to apply a filter to view black games by this player", that would effectively be the same logic as OpeningTree, but it would just be better because you can have engine analysis and all of the other features that en-croissant offers.

**Comment by franciscoBSalgueiro** [comment]
This was added in https://github.com/franciscoBSalgueiro/en-croissant/commit/6c9fd30887dd2632cc4d12cbb7f2cd01e2231421
