### ISSUE TITLE
Native title bar disappears

### ISSUE THREAD

**Issue by F0r9e** [franciscoBSalgueiro/en-croissant#197]
### Describe the bug

The title bar (native appearance) will disappear on start up.
Cannot reproduce on version 0.9.1 and below.

![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/61375029/24ce17cd-a383-4ccd-872a-44b29bc4b887)

### Reproduction

1. Settings -> Appearance -> Title Bar -> "Native"
2. Restart program

### Platform and versions

Windows 11
0.9.2 Pre-release

**Comment by franciscoBSalgueiro** [comment]
Fixed by https://github.com/franciscoBSalgueiro/en-croissant/commit/898474d3e0e06fa00e4e0e7e21d412f09b623440
