### ISSUE TITLE
LC0 not available for install on MacOS

### ISSUE THREAD

**Issue by JarlAmbiorix** [franciscoBSalgueiro/en-croissant#199]
### Describe the bug

LC0 is not available as an engine

### Reproduction

open the engine section and when clicking on add new you can not add LC0

### Platform and versions

Mac OS

**Comment by franciscoBSalgueiro** [comment]
Not a bug, the only builds of Lc0 available for download are for Windows and Android.

https://github.com/LeelaChessZero/lc0/releases/tag/v0.30.0

**Comment by razum2um** [comment]
There're bottles built by homebrew: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/l/lc0.rb#L9
