### ISSUE TITLE
Cannot add  engines on MacOS

### ISSUE THREAD

**Issue by kenpchess** [franciscoBSalgueiro/en-croissant#2]
Hello, interesting software! I cannot add an engine under the Mac OS version of en-crossant. It seems that all engine binaries are greyed-out under the local file selection (the download option seems to work, though). (I have dozens of UCI and WindBoard engines, I compile them myself and they work fine under cutechess, BanksiaGUI, etc). I hope you keep improving en-croissant, it is "rough around the edges" but very interesting. Thanks!  --kenpchess

**Comment by franciscoBSalgueiro** [comment]
Hey, thanks for the report! I've just fixed that for the next version. Meanwhile, I believe there should be an option to change the file type to "All files" in the file picker dialog that will allow you to choose any binary.

**Comment by kenpchess** [comment]
Hello Francisco! Thanks for your attention to the bug. Sorry, but I do not see any option under Mac en-croissant to select file-type or allow all files. Probably have to wait for you to push the new release. Thanks again. - kenpchess

P.S. - when you get time could you publish more detailed build-from-source instructions for mac-os en-croissant?

**Comment by franciscoBSalgueiro** [comment]
I've released a new version with the fix. Let me know if it's working for you (unfortunately I don't own a Mac to test it myself).

Regarding the build instructions, did you face any particular issues?
