### ISSUE TITLE
Add the possibility to train from a PGN

### ISSUE THREAD

**Issue by Cassandre60** [franciscoBSalgueiro/en-croissant#200]
### Describe the feature

Like in a Lichess study, in Chessable or in Chess Tempo, having the possibility to play very line stored in a PGN is an extremely important feature for all chess levels.
A basic version of simply getting to play a random line at a time of out the file would be a great first step.

**Comment by franciscoBSalgueiro** [comment]
This already exists.

https://encroissant.org/docs/guides/manage-repertoire#practice-mode

**Comment by Cassandre60** [comment]
The already implemented practice feature is somewhat different from the ones available in the sites I mentioned above.
First, I can't directly import a PGN and directly start "practice" on it right away (I need to create a repertoire first). Secondly, in these other sites, you just play one color and the game automatically chooses a response while in en croissant you have to click practice next position every time which is very impractical. There is also the problem of forcing me to fill the file "by hand" in the repertoire, while I want mostly to use my already constructed file.

Some of these might not be a real issue and just my ignorance about en croissant since I am a new user, but making these tasks as simple and intuitive as possible will probably help new users like me navigate the program better.

**Comment by franciscoBSalgueiro** [comment]
Can you explain what you mean by filling the file "by hand"?

**Comment by franciscoBSalgueiro** [comment]
Not at all, feel free to open more issues!

I've just added that extra option directly in the Import Game (https://github.com/franciscoBSalgueiro/en-croissant/commit/c31b23c632e60e1782752c44c79bca0eb2f187bd)

**Comment by Cassandre60** [comment]
Thanks.
