### ISSUE TITLE
Unable to paste PGN during Import Game (MacOS)

### ISSUE THREAD

**Issue by mrnohr** [franciscoBSalgueiro/en-croissant#202]
### Describe the bug

When I am trying to copy a game and paste it into En Croissant as part of the Import game feature, I am not able to paste it. I can type in the PGN game field, but not paste. If I right-click and choose paste, then it the game will be added to the text box, but not using the keyboard shortcut.

This is specifically on MacOS

### Reproduction

1. Copy game onto clipboard. For example, from Lichess choose "Copy PGN"
2. Go to New Tab
3. Click "Import" under "Import Game"
4. Choose "PGN" as Type of Import
5. Put your cursor in the "PGN game" field
6. Use the keyboard shortcut to paste, ⌘-V
7. See that nothing happens

### Platform and versions

Mac OS: Darwin x86_64 14.3.1
En Croissant: 0.9.2

**Comment by franciscoBSalgueiro** [comment]
Does it work if you select the native Title Bar in Settings > Appearance?

**Comment by mrnohr** [comment]
I tried that and there was the same behavior. Not able to paste using keyboard shortcuts, but I can if I right-click and choose paste

**Comment by anderslundback** [comment]
This is not unique to the PGN field, I can't copy/paste regular comments on a move either using the keyboard shortcut, but right click + select paste works.

I noticed I can't copy from en-croissant either using the keyboard. Is there an OS security option to allow this?

Version: 0.9.2
Tauri version: 1.5.2
OS: Darwin x86_64 13.6.3

**Comment by franciscoBSalgueiro** [comment]
I don't have a Mac to test this. I followed [this](https://github.com/tauri-apps/tauri/issues/2397) recommendation with https://github.com/franciscoBSalgueiro/en-croissant/commit/a52d012af1493c33d83e378f936c61aded8db520.

**Comment by mrnohr** [comment]
I built from source on a Mac, which included the https://github.com/franciscoBSalgueiro/en-croissant/commit/a52d012af1493c33d83e378f936c61aded8db520 commit. Now I am able to paste into this box.

Looks like it is solved! Thanks.
