### ISSUE TITLE
Each time you click 'Download games' for a user, it adds a copy of every game with Ply count = 0

### ISSUE THREAD

**Issue by pure-blue** [franciscoBSalgueiro/en-croissant#218]
### Describe the bug

I searched the issues for this, and while there are issues about the percentage of downloaded games being > 100%, I didn't see anything about this specifically.

In the Databases window, each of my games is followed by three copies of that game in which Ply count = 0. Maybe I'm missing something and this isn't a bug, I'm not sure.

<img width="343" alt="Screenshot 2024-02-21 at 11 00 41 AM" src="https://github.com/franciscoBSalgueiro/en-croissant/assets/79292724/04b56c76-3d36-4d33-b256-941fc332f226">

### Reproduction
 
1. Click on Databases to the left

***

> [!NOTE]
> After further investigation I found what seems to be causing this, i.e. the real bug:

### Describe the bug

Right after I posted the Issue above, I noticed that in my screenshot below, my most recent game doesn't have _three_ Ply count = 0 copies, but just one. I then went to the User page and clicked on the button to download my games again. I went back to Databases page and saw that the number of Ply count = 0 copies increased by one for each game. Each time I go back and click the button to download my games, the number of Ply count = 0 copies increases by one. So I guess at the time that I initially posted this issue, I had downloaded my games three times. I also noticed that the percentage of downloaded games on the user page increases each time I click the button to download my games, so it appears that this that issue is related to issue #54 concerning percentage of games downloaded. Each time you click 'Download games', it also doubles the number of games listed on the stats pane of the User page, but not the number of games listed for that user on the "Accounts" pane. (I thought that a bandaid would be doing "Delete account" on the User page and reconnecting my account, but all of the Ply = 0 copies are still there after I do this. Is there a way to actually reset the downloaded games so the Ply = 0 games disappear?)

### Reproduction

1. Add a chess.com user on the Users page
3. Download your games
4. Play some more games and want to update your downloaded games so that the new games are included
5. Click "Download games" again to achieve this
6. Go to Databases and click on your user
7. Click "Explore" where you will see that while it did add your new games, it also added a copy of every previously downloaded game, each copy having Ply count = 0 (indicating no moves played).
8. Go back to the Users page to see that 1) Percentage of downloaded games has increased even further above 100%
9. Click "Update stats" to see that "# Games" on the stats panel has also increased, although "# Games" for that user on the Accounts panel has not changed.

### Platform and versions

macOS 14.2.1 23C71 arm64

**Comment by franciscoBSalgueiro** [comment]
I'm also adding two new buttons to help removing these duplicates:
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/92053465/b206b99e-1eb9-4299-978e-c26cc13dedf4)

**Comment by pure-blue** [comment]
@franciscoBSalgueiro Thanks a lot! Forgive my ignorance, how do I implement these changes? Do I need to wait for an app update, or is there a way to integrate the changes in the code myself?
