### ISSUE TITLE
Add more annotation glyphs

### ISSUE THREAD

**Issue by anderslundback** [franciscoBSalgueiro/en-croissant#220]
### Describe the feature

As a user,
I'd like more annotation glyphs,
So that I can more easily annotate my games

#### Inspiration
Chessdojo training program game editor (description on mouseover)
<img width="504" alt="image" src="https://github.com/franciscoBSalgueiro/en-croissant/assets/8585021/487534b3-8d15-4640-b5c2-639c03c80fd5">

lichess studies:
<img width="764" alt="image" src="https://github.com/franciscoBSalgueiro/en-croissant/assets/8585021/39cefdaf-4a94-4292-9ec8-7f91b953ab4b">

Current en-croissant buttons:
<img width="844" alt="image" src="https://github.com/franciscoBSalgueiro/en-croissant/assets/8585021/a88e310c-6062-4dc8-bca5-8df73d708090">

**Comment by tegenterter** [comment]
I came here to suggest the same, at the bare minimum evaluations should be supported

**Comment by franciscoBSalgueiro** [comment]
Added in https://github.com/franciscoBSalgueiro/en-croissant/commit/56e0202368cb5a2e189a78462b6d08316ca23341
