### ISSUE TITLE
Strange result of clicking "FIDE info" button on Accounts page (random player shown)

### ISSUE THREAD

**Issue by pure-blue** [franciscoBSalgueiro/en-croissant#225]
### A seemingly random player appears when I click the "FIDE info" button on the User page stats panel.

I noticed the "info" symbol (circle with an "i" inside) at the top right corner of the stats that appears on the right side of the window when you click on a user. I was curious what it was but when I clicked on it, it said something like "No FIDE information downloaded", and there was a button to download. I clicked that, it took a bit to complete, and once it was finished I clicked the FIDE info button again. This time, this appeared:

<img width="347" alt="Screenshot 2024-02-27 at 2 14 43 AM" src="https://github.com/franciscoBSalgueiro/en-croissant/assets/79292724/f981ba96-306e-4f90-9291-e85f7df49bf5">

I don't know who this is or why that player in particular is appearing. When I click the cloud button I'm brought to [this page](https://www.chessabc.com/en/rating-list/proestler-andre).

Couldn't find anything about this in your documentation.

Love your app!

### Reproduction

1. Go to the User page by clicking on the User button on the left sidebar.
2. Click on my chess.com account.
3. Click on the "FIDE info" button at the top right corner of the stats panel.

### Platform and versions

macOS 14.3.1 23D60 arm64

**Comment by pure-blue** [comment]
Oh, I see. It seems like it's looking for the name I gave the account in the FIDE database and if that name isn't there, it finds a player that _is_ in the FIDE database with the closest (by some metric) name as the one I gave the user (I just gave it my chess.com username, but when I changed the user name to "Me", clicking on the FIDE info symbol resulted in this window:

<img width="344" alt="Screenshot 2024-02-27 at 2 40 06 AM" src="https://github.com/franciscoBSalgueiro/en-croissant/assets/79292724/95865338-2e2f-4d43-aea7-d69ac787105a">

**Comment by franciscoBSalgueiro** [comment]
Yes, that's the intended behavior. Maybe it should be clearer which name is being searched. Something like "closest match to '<name>'" next to the found name.

**Comment by pure-blue** [comment]
Yeah, or just adding something in the documentation could be sufficient. Thanks for your reply. Now I want a FIDE profile... ;-)
