### ISSUE TITLE
Automatic (AI) comment generation

### ISSUE THREAD

**Issue by dxkill** [franciscoBSalgueiro/en-croissant#230]
### Describe the feature

Not only the ability to make a game report, but also a toggle to activate the new feature, an (AI model) automatic comment generator, that either generates comments for every move or for significant moves only.

**Comment by franciscoBSalgueiro** [comment]
An AI model is way out of scope for this project

**Comment by dxkill** [comment]
I mean, it doesnt have to be AI...

Francisco Salgueiro ***@***.***> schrieb am Do., 29. Feb.
2024, 17:25:

**Comment by dxkill** [comment]
AI is absoloutely optional. I just thought that some really basic comments like "This move drops the Knight" would be essential for automatic game review.

**Comment by franciscoBSalgueiro** [comment]
Move descriptions in the report were already suggested in https://github.com/franciscoBSalgueiro/en-croissant/issues/108. There's also an experimental branch https://github.com/franciscoBSalgueiro/en-croissant/tree/report-comments with some very basic comment generation.

**Comment by dxkill** [comment]
Alright, do you think you will put this branch into a main release sometime, after debugging of course?

**Comment by franciscoBSalgueiro** [comment]
Maybe, I didn't merge it because I wasn't satisfied with the result. I'd rather have no descriptions than bad descriptions.
