### ISSUE TITLE
Lichess All Database does not load up and cause an error

### ISSUE THREAD

**Issue by algothemi** [franciscoBSalgueiro/en-croissant#233]
### Describe the bug

When trying to to show Lichess All database stats on the app,
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/144251310/c6541539-4c94-4ca8-8058-f1a1ecdbd494)

The following error occurs:
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/144251310/08971879-4462-40a2-98ac-18912d5bde6c)

### Reproduction

1. Go to Analysis Board
2. Click Database Tab
3. Switch from "Local" Databases to "Lichess All"
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/144251310/08971879-4462-40a2-98ac-18912d5bde6c)

"Lichess Masters" is working as intended.

### Platform and versions

Windows 10 Pro

### Stack trace

```Shell
e.toISOString is not a function
TypeError: e.toISOString is not a function
    at wOe (https://tauri.localhost/assets/index.js:244:5185)
    at KP (https://tauri.localhost/assets/index.js:244:5298)
    at PT (https://tauri.localhost/assets/index.js:38:19552)
    at bZ (https://tauri.localhost/assets/index.js:40:44104)
    at gZ (https://tauri.localhost/assets/index.js:40:39822)
    at Afe (https://tauri.localhost/assets/index.js:40:39748)
    at rg (https://tauri.localhost/assets/index.js:40:39598)
    at Xz (https://tauri.localhost/assets/index.js:40:35960)
    at q$ (https://tauri.localhost/assets/index.js:40:36765)
    at R1 (https://tauri.localhost/assets/index.js:38:3288)
```

**Comment by Groglet** [comment]
I'm experiencing the same issue with the linux appimage. Deleting everything in
`~/.local/share/org.encroissant.app/localstorage/`
and restarting the app seems to fix the issue temporarily - at least until I create a new repertoire, upon which the database immediately breaks as described by OP.

**Comment by algothemi** [comment]
Similar to @groglet , deleting the app's storage folder on Windows fixed the issue I think. I am not sure if the error will happen again, but for now I have been using the Lichess DB without any issues.

C:\Users\[user]\AppData\Local\org.encroissant.app\EBWebView\Default\Local Storage\leveldb\

If it happen again, I might delete the folder's contents again.

**Comment by gennaro-tedesco** [comment]
I am seeing a similar error with the Lichess Master database instead, whilst the Lichess All works just fine.

Below is the stacktrace
```
e.toISOString is not a function. (In 'e.toISOString()', 'e.toISOString' is undefined)
wOe@tauri://localhost/assets/index.js:244:989767
@mantine/dates/HiddenDatesInput@tauri://localhost/assets/index.js:244:989872
PT@tauri://localhost/assets/index.js:38:88149
bZ@tauri://localhost/assets/index.js:40:140781
gZ@tauri://localhost/assets/index.js:40:136499
Afe@tauri://localhost/assets/index.js:40:136425
rg@tauri://localhost/assets/index.js:40:136276
Xz@tauri://localhost/assets/index.js:40:132637
q$@tauri://localhost/assets/index.js:40:133442
q$@[native code]
R1@tauri://localhost/assets/index.js:38:71885
u2@tauri://localhost/assets/index.js:40:133890
FY@tauri://localhost/assets/index.js:37:39978
ex@tauri://localhost/assets/index.js:37:64193
pT@tauri://localhost/assets/index.js:37:48336
v2e@tauri://localhost/assets/index.js:37:48119
v2e@[native code]
```

If it matters, I am on a `macOS 12.7.3 Monterey`.

**Comment by franciscoBSalgueiro** [comment]
Fixed by https://github.com/franciscoBSalgueiro/en-croissant/commit/7846e5f75d51c52665e7d7a04474f791fe66da18
