### ISSUE TITLE
New Tab adds new Tabs but they're not displayed properly

### ISSUE THREAD

**Issue by illuminat281090** [franciscoBSalgueiro/en-croissant#235]
### Describe the bug

Board -> File -> New Tab
Let it be Import but I believe there is the same behavior for others, it's more about UI issues
If you fill with opened Tabs all the header 
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/24498981/a194188c-ceb4-4b30-9285-dea6024b1c6e)
So, we got to the situation when Tabs far away from the border, and you can add more, they're actually appear
But
1. If you click on the Tab which is Marked with Red on the screenshot above - you just jump on its content, but Tab itself still remains "hidden", either partially visible or somewhere outside at all, just as you see on screen above
2. You can't really scroll amongst other Opened Tabs. But if you close some - they move back, one by one

So, to fix it and make it more comfortable it good to have each tab autoscalable like web browsers do and add buttons Right/Left to switch and jump between all other tabs (or add some kind of Table Content or similar)

### Reproduction

1. Board -> File -> New Tab
2. Let it be Import Game
3. Do import
4. Repeat 1-3 a couple of times, till Opened Tabs exceed header's borders
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/24498981/a194188c-ceb4-4b30-9285-dea6024b1c6e)

### Platform and versions

![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/24498981/29df7487-5c98-4cab-ac20-4f6c5ab4e6f3)

**Comment by franciscoBSalgueiro** [comment]
I've also removed "(Imported)" from the tab name, so the scrollbar is less likely to be needed
