### ISSUE TITLE
Crash when dowloading any DB

### ISSUE THREAD

**Issue by dr4kan** [franciscoBSalgueiro/en-croissant#241]
### Describe the bug

MacOs 14.2.1 (23C71)

When I try to download any database (from those in the list) at some point during the downloading the app crashes.

**Comment by dr4kan** [comment]
The problem seems to be related to

`            DownloadProgress {
                progress,
                id: id.clone(),
                finished: false,
            }
            .emit_all(&app)?;
`

in fs.rs file. Indeed, if commented the database is downloaded correctly. Ideas?

**Comment by franciscoBSalgueiro** [comment]
Maybe it's because progress is f64, which maybe can be too big to be properly de/serialized to javascript.
https://github.com/franciscoBSalgueiro/en-croissant/commit/85e911bd1625ac99256c28afd256f145dd9908a2 changes it to f32 which might fix it
