### ISSUE TITLE
Upload of pgn files > 1Mb as database lasts indefinitely

### ISSUE THREAD

**Issue by gennaro-tedesco** [franciscoBSalgueiro/en-croissant#244]
### Describe the bug

Thank you very much for the awesome software, this is a great effort and a fantastic product!

I have noticed that when uploading big pgn files as databases, the conversion (or upload) freezes if the size of the file is approximately 1Mb. For any smaller pgn the process works smoothly in a fraction of second - however when the size grows I have been unable to upload.

Is there a way I can produce some stacktrace or debugging logs for this type of situation? What I observe is merely that the upload loading status lasts forever (I assume the process stops at some point due to some sort of timeouts but the interface still shows the spinner running).

### Reproduction

1. Upload any pgn file >1Mb as database 
2. Wait for the upload to complete
3. The upload freezes

### Platform and versions

```
macOS 12.7.3 Monterey
processor: 2,2 GHz Quad-core Intel Core i7
```

**Comment by franciscoBSalgueiro** [comment]
There are no uploads, everything is done locally. I'm able to do conversions, so it's probably an issue with the PGNs you're trying to convert. Can you send one of them?

**Comment by gennaro-tedesco** [comment]
> There are no uploads, everything is done locally. 

Sorry, I didn't express myself correctly, I did indeed mean local conversion.

> it's probably an issue with the PGNs you're trying to convert. Can you send one of them?

Yes, after your comment I went and debugged the `pgn` causing problems and it seems that whenever a file contains the entry
```
[WhiteElo "..."]
[BlackElo "..."]
```
the conversion fails: you can reproduce with the following:
```[Event "Moscow CC Spring Tournament"]
[Site "Moscow"]
[Date "1907.06.04"]
[Round "1"]
[White "Alekhine, Alexander"]
[Black "Rozanov, Vasily I"]
[Result "1-0"]

1. e4 e5 2. Nf3 Nc6 3. d4 exd4 4. Nxd4 Nf6 5. Nxc6 bxc6 6. Bd3 d5 7. exd5 cxd5
8. O-O Be7 9. Nc3 O-O 10. Bg5 c6 11. Qf3 Bg4 12. Qg3 Bh5 13. Qe5 Bg6 14. Bxg6
hxg6 15. Rad1 Bd6 16. Qd4 Qc7 17. Qh4 Nh7 18. Be3 f5 19. f4 Kf7 20. Bd4 Rh8 21.
Rde1 Nf6 22. Qg5 Ng4 23. Re6 Kxe6 24. Qxg6+ Kd7 25. Qxf5+ Kd8 26. Qxg4 Bf8 27.
Re1 Qd7 28. Qg5+ Kc7 29. Re3 Kb7 30. Na4 Re8 31. Rb3+ Ka8 32. Qg3 Rh6 33. Qd3
Rhe6 34. Be5 c5 35. Rb5 Rc8 36. c4 a6 37. Nb6+ Rxb6 38. Rxb6 Ka7 39. Qg6 Qa4
40. Rb3 Qc6 41. Qf7+ Ka8 42. cxd5 1-0
```
which fails if turned into
```
[Event "Moscow CC Spring Tournament"]
[Site "Moscow"]
[Date "1907.06.04"]
[Round "1"]
[White "Alekhine, Alexander"]
[Black "Rozanov, Vasily I"]
[WhiteElo "123"]
[BlackElo "123"]
[Result "1-0"]

1. e4 e5 2. Nf3 Nc6 3. d4 exd4 4. Nxd4 Nf6 5. Nxc6 bxc6 6. Bd3 d5 7. exd5 cxd5
8. O-O Be7 9. Nc3 O-O 10. Bg5 c6 11. Qf3 Bg4 12. Qg3 Bh5 13. Qe5 Bg6 14. Bxg6
hxg6 15. Rad1 Bd6 16. Qd4 Qc7 17. Qh4 Nh7 18. Be3 f5 19. f4 Kf7 20. Bd4 Rh8 21.
Rde1 Nf6 22. Qg5 Ng4 23. Re6 Kxe6 24. Qxg6+ Kd7 25. Qxf5+ Kd8 26. Qxg4 Bf8 27.
Re1 Qd7 28. Qg5+ Kc7 29. Re3 Kb7 30. Na4 Re8 31. Rb3+ Ka8 32. Qg3 Rh6 33. Qd3
Rhe6 34. Be5 c5 35. Rb5 Rc8 36. c4 a6 37. Nb6+ Rxb6 38. Rxb6 Ka7 39. Qg6 Qa4
40. Rb3 Qc6 41. Qf7+ Ka8 42. cxd5 1-0
```
Reading around I found conflicting information on whether `[WhiteElo "..."]` is an accepted parameter for a pgn file.

Obviously I will solve the problem just removing those entries in all my files for the moment, however _if_ you want to consider making conversion available for files containing such entries too I can open a corresponding issue (clearly this one turned out to be false, the problem being hidden in some specific files which "accidentally" were big, thus I though the size be the problem).

**Comment by franciscoBSalgueiro** [comment]
Thanks! It should no longer crash when the ELOs aren't numeric
