### ISSUE TITLE
README Contains Dead Link

### ISSUE THREAD

**Issue by 53142** [franciscoBSalgueiro/en-croissant#258]
### Describe the feature

The README file contains a dead link. As shown in the screenshot below, the _src-tauri/target/release_ text contains a link to a file that does not exist anymore (https://github.com/franciscoBSalgueiro/en-croissant/blob/master/src-tauri/target/release).

![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/89957019/061076e0-0b82-4980-834d-036f06a965f7)

**Comment by franciscoBSalgueiro** [comment]
Thanks for catching that, it was never meant to be a link. That directory is generated when compiled
