### ISSUE TITLE
en-croissant: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Kushagra2007** [franciscoBSalgueiro/en-croissant#276]
I'm using Ubuntu 22.04.3 on WSL. I installed en-croissant and converted it to executable, then I started getting this error message. I then manually started installing all libraries using apt in the error, but they are too many, so I uninstalled them. I found that for software using shared libraries, you need to add them to path but I don't know for .AppImage. Am I missing something?

**Comment by franciscoBSalgueiro** [comment]
I tried installing the libraries it said were missing until it worked:

`apt install libegl1 libharfbuzz0b libopengl0 libglvnd-dev libfribidi-dev libthai0`

Never thought about using WSL though. May I ask why you are you doing it in WSL instead of windows?

**Comment by Kushagra2007** [comment]
Sorry for late reply. It's easier to manage packages and most of my work is on linux so why not. Another reason is that I find it quite annoying that if you uninstall an application in windows, there's often some residue left that you have to manually delete to get the satisfaction of completely removing it (and freeing up that extra 2mb space ).
