### ISSUE TITLE
More piece sets and boards 

### ISSUE THREAD

**Issue by dan-peters-go** [franciscoBSalgueiro/en-croissant#283]
### Describe the feature

Hi! Just found your app and it looks amazing. 
The one thing I would love to request is for you to add more different styles for pieces and boards. In particular, I'd love to see the options from chess.com.

I play on lichess myself, but prefer the visuals of chess.com and there's an extension for that. Probably you could use the recources from this extension: https://github.com/ducksper/lichess_enhancement

**Comment by franciscoBSalgueiro** [comment]
Those assets are not free to use (they belong to chess.com) so I won't include them.
