### ISSUE TITLE
engine playing from position often doesn't work

### ISSUE THREAD

**Issue by ChaseRensberger** [franciscoBSalgueiro/en-croissant#290]
### Describe the bug

When you set up a position in **Analysis** and then select **Play from here** then set the player parameters. Pressing **Start game** will start a game from the default starting position.

### Reproduction

1. Go to analysis
2. set up custom position
3. select play from here
4. configure 2 engines for simulation
5. press start game

### Platform and versions

MacOS 14.3.1 (23D60)

**Comment by ChaseRensberger** [comment]
i'm going to investigate this further

**Comment by Kristinita** [comment]
@ChaseRensberger , how did you solve this problem?

Thanks.
