### ISSUE TITLE
Allow the Variation tree to show pieces Icons instead of letters

### ISSUE THREAD

**Issue by Cankyre** [franciscoBSalgueiro/en-croissant#291]
### Describe the feature

The title speaks for itself. Showing icons is also recommended by FIDE (Handbook rules annex 3). It could also help with #279 as having pieces icons would not require the Game notation to have that much of a translation.

Should be a toggle in the settings

**Comment by Scoutboy06** [comment]
This has been merged in #297, thanks for the suggestion!
