### ISSUE TITLE
Skill level can be negative

### ISSUE THREAD

**Issue by guyru** [franciscoBSalgueiro/en-croissant#294]
### Describe the bug

In the advanced settings for engine one should be able to set negative values to Skill Level. It's supported by stockfish and used for example for the easy settings by [lichess](https://github.com/lichess-org/fishnet/blob/master/src/api.rs#L208)

### Reproduction

1. Add stockfish as an Engine
2. Try setting skill level to a negative value (say -9)
3. Skill level gets reverted to 0.

### Platform and versions

Debian

**Comment by franciscoBSalgueiro** [comment]
The minimum value is defined by the engine. The minimum SkillLevel for stockfish is 0 as can be seen on its [documentation](https://github.com/official-stockfish/Stockfish/wiki/UCI-&-Commands)

**Comment by guyru** [comment]
It looks like you're right according to the docs. Not sure how it works for [lichess](https://github.com/lichess-org/fishnet/blob/master/src/api.rs#L260).
