### ISSUE TITLE
Board position resets on toggle edit in certain circumstances

### ISSUE THREAD

**Issue by jez9999** [franciscoBSalgueiro/en-croissant#304]
### Describe the bug

I've noticed the board position resetting on toggle edit in certain circumstances.  I suspect it's to do with the following code:

https://github.com/franciscoBSalgueiro/en-croissant/blob/8b5c1aca95740ab44635caa5997aed9e11ecea81/src/components/boards/Board.tsx#L471-L475

Why `boardFen` gets out of sync with `currentNode.fen` I don't know.

### Reproduction

1. Open a new analysis board
2. Toggle 'edit position' and move a piece
3. Exit editing mode
4. Run engine analysis
5. Click on an engine analysis line
6. Toggle 'edit position' again (board position resets to what it was before you clicked on the analysis line)

### Platform and versions

Windows 10, version 0.10.0.

**Comment by jez9999** [comment]
When the board position resets, it also erases the whole moves list.

**Comment by franciscoBSalgueiro** [comment]
This should fix both problems
