### ISSUE TITLE
Allow left-click to clear notations

### ISSUE THREAD

**Issue by jez9999** [franciscoBSalgueiro/en-croissant#310]
### Describe the feature

On lichess, the notations made with right-clicks (circles and arrows) are cleared in you left-click on the board, which is useful.  Please implement the same behaviour in En Croissant (currently you have to press Ctrl-L).

**Comment by franciscoBSalgueiro** [comment]
Not planned, it was intentionally made a shortcut so it's not as easy to accidentally clear the arrows.

**Comment by jez9999** [comment]
It's a PITA to press the shortcut though.  Maybe it could be a setting?

**Comment by franciscoBSalgueiro** [comment]
You can change the shortcut to anything you like

**Comment by jez9999** [comment]
I can't seem to change it to left click, though.  I don't wanna have to reach to the keyboard each time to clear the annotations. :-)
