### ISSUE TITLE
Chess.com download doesn't work.

### ISSUE THREAD

**Issue by arduinocodedog** [franciscoBSalgueiro/en-croissant#32]
Adding a Chess.com account works, but when the option to download games is clicked it doesn't work and the wait indicator just spins.  The downloads never occur.  Lichess downloads are working fine.

**Comment by kevinjose** [comment]
Facing this issue on v0.8.0 from https://www.encroissant.org/download

Tried on
- Mac M1 Air
- Mac M2 Air
Running MacOS Sonoma 14.0

Happy to provide more info, if req.
