### ISSUE TITLE
en-croissant 0.11.0_aarch64.dmg doesn't work

### ISSUE THREAD

**Issue by poparotsy** [franciscoBSalgueiro/en-croissant#342]
### Describe the bug

<img width="372" alt="en-croissant-installation-error" src="https://github.com/user-attachments/assets/0eef30a0-271f-42fe-8d32-7a2af2f59966">

### Reproduction

On MacPro M1

1. Download en-croissant_0.11.0_aarch64.dmg from GitHub _The download link on https://encroissant.org/ throws 404_
2. Try installing the app.

### Platform and versions

MacBookPro M1
en-croissant_0.11.0_aarch64.dmg

**Comment by PaulJeFi** [comment]
I have the same problem on MacBook Air Intel

**Comment by franciscoBSalgueiro** [comment]
I've tried reversing to macos-13. Can you try the pre-release version to see if it fixed it?

https://github.com/franciscoBSalgueiro/en-croissant/releases/download/master-beta/en-croissant_0.11.0_x64.dmg

**Comment by supcik** [comment]
I also had the same problem. I just tried your pre-release and it seems to work. Thank you.

**Comment by PaulJeFi** [comment]
Works fine now, thanks !
