### ISSUE TITLE
download for MacOS does not work

### ISSUE THREAD

**Issue by Himbeereis** [franciscoBSalgueiro/en-croissant#345]
### Describe the bug

download for MacOS does not work

### Reproduction

download for MacOS does not work

### Platform and versions

 MacOS

### Stack trace

```Shell
?
```

**Comment by franciscoBSalgueiro** [comment]
Thanks, the link has been fixed

**Comment by gennaro-tedesco** [comment]
I am on a MacOs Monterey 12.7.6 and apparently the new version cannot be installed (as in "not supported"). Has the new version introduced some specific requirements for it to be run on newest MacOs only?
