### ISSUE TITLE
Invalid castling rights

### ISSUE THREAD

**Issue by at672** [franciscoBSalgueiro/en-croissant#346]
### Describe the bug

Every time I move the pieces while the engine is running, I get invalid castling rights. I can try manually deselecting the checkboxes in the bottom right but it doesn't fix the issue. Before the latest version it was very easy to use and put in whether or not you could castle. Now you can't. It's extremely unintuitive and I cannot get it to work when trying to manually set up positions for analysis. I have no idea how to make it work and I think this needs to be fixed for better understandability and usability by the end-user.

### Reproduction

1. Go to analysis tab.
2. Start the engine (whichever you prefer, it doesn't matter).
3. Click on the edit button
4. Click and drag the king to one of the rooks to manually castle pieces
5. the error appears.

Also, if you empty the board and then set up the pieces directly, the error still appears even though I never actually castled.

### Platform and versions

Windows 11. Latest version of en croissant after downloading the update

### Stack trace

```Shell
Error: Invalid castling rights.
```

**Comment by morphogeneticengineering** [comment]
Hi! I get this error with Chess960 games, various puzzles, other times when I am editing a board into a custom position or from FEN and it seems to not be engine related but croissant related.

**Comment by franciscoBSalgueiro** [comment]
050acb5707ff7ae1ec9fd451ad261c0dab9f6c63 should have fixed this issue.

**Comment by emmachristine717** [comment]
> [050acb5](https://github.com/franciscoBSalgueiro/en-croissant/commit/050acb5707ff7ae1ec9fd451ad261c0dab9f6c63) should have fixed this issue.

Hi, I'm on the latest version of the program and I've having this exact same error. has this patch already been added or do I have to install it myself.
Apologies for my computer illiteracy, I'm just trying to play some chess.

**Comment by at672** [comment]
Confirmed, I'm on the latest version, I can't get any updates, and I still have invalid castling rights bug when setting up a position.

The bug seems to happen when you take white piece and use that to overwrite a black rook, or vice versa. Something in the code makes it want those rooks to stay there when setting up a position.

A smarter way to address this is to have castling turned off by default, and then you have to manually click the buttons to show case that castling is still possible, and then check the piece positions to ensure that castling actually is possible, and only then throw an error.

It's also extremely frustrating that you get the error dialogue box like 5 times.
