### ISSUE TITLE
I download the Master branch and compile it and when I open en-croissant the new added languages ​​do not appear.

### ISSUE THREAD

**Issue by yako1984** [franciscoBSalgueiro/en-croissant#351]
### Describe the bug

I download the Master branch and compile it and when I open en-croissant the new added languages ​​do not appear.

### Reproduction

1. Ejecutar en-croissant
2. Ir a configuración
3. Language

### Platform and versions

Master

**Comment by franciscoBSalgueiro** [comment]
Does this still happen? The releases are built from master so they should be appearing

**Comment by yako1984** [comment]
Nothing is solved, you can close it, it was my mistake, I was running the app without ./, so I was running the version that I had on my PC and not the new one.
I'm sorry

all the best

**Comment by yako1984** [comment]
solved
