### ISSUE TITLE
App windows size is not persistent on MacOS

### ISSUE THREAD

**Issue by seuaCoder** [franciscoBSalgueiro/en-croissant#354]
### Describe the bug

WHen i resize the window and restart the app, the app is always full screen. 

### Reproduction

- Open En Croissant on MacOS
- Resize the window
- Cclose the app
- Reopen the app

### Platform and versions

Version: 0.11.0
Tauri version: 1.6.1
OS: Darwin x86_64 14.5.0

**Comment by franciscoBSalgueiro** [comment]
Fixed by #407
