### ISSUE TITLE
Failure to load next positions in repertoire practice training

### ISSUE THREAD

**Issue by seveer** [franciscoBSalgueiro/en-croissant#364]
### Describe the bug

In the attached (see reproduction) repertoire I'm training, I reach a certain move after which I can not progress. I can make the correct move 5. O-O over and over, and it will show as correct in the training log, but every time I try to proceed to next move it simply returns me to this position and I can't train the remaining 90% of the repertoire. It can't be skipped. 

FYI this is a repertoire PGN exported directly from chessbook.com.

### Reproduction

1. Load PGN (below) as a repertoire.
2. Train up to 1. e4 c5 2. Nf3 d6 3. Bb5+ Nc6 4. Bxc6+ bxc6
3. Make the move 5. O-O

PGN: 1. e4 c5  (1... e5  2. Nf3 Nc6  (2... d6  3. Bc4 Bg4  (3... h6  4. d4 exd4 5. c3) 4. h3)  (2... Nf6  3. d4 exd4  (3... Nc6  4. dxe5) 4. e5)  (2... Bc5  3. Nxe5) 3. d4 exd4  (3... d6  4. Bb5 Bd7 5. Nc3)  (3... Nf6  4. dxe5) 4. Bc4 Nf6  (4... Bc5  5. c3 dxc3 6. Bxf7+ Kxf7 7. Qd5+ Ke8 8. Qh5+ g6 9. Qxc5)  (4... h6  5. c3 dxc3 6. Qb3 Qe7 7. Nxc3)  (4... d6  5. c3 dxc3 6. Qb3 Qe7 7. Nxc3 Nf6 8. O-O g6 9. Bg5 Bg7 10. Nd5 Nxd5 11. exd5 Na5 12. Qa4+ Qd7 13. Bb5 c6 14. Rae1+ Kf8 15. Qxa5 cxb5 16. Re7 h6 17. Rxd7 Bxd7 18. Bf4 b6 19. Qa3 Kg8 20. Qxd6)  (4... Bb4+  5. c3 dxc3 6. O-O) 5. e5 d5  (5... Ng4  6. O-O) 6. Bb5 Ne4 7. Nxd4 Bd7 8. Bxc6)  (1... e6  2. d4 d5  (2... c5  3. d5) 3. Nd2 c5 4. Ngf3)  (1... d5  2. exd5 Qxd5  (2... Nf6  3. d4 Nxd5 4. c4 Nf6 5. Nc3 Bf5 6. Qf3 e6 7. Qxb7) 3. Nc3 Qa5  (3... Qd8  4. d4) 4. Bc4)  (1... c6  2. d4 d5 3. Nd2 dxe4 4. Nxe4 Bf5 5. Ng3 Bg6 6. h4 h6 7. Nf3)  (1... g6  2. d4 Bg7 3. Nc3)  (1... d6  2. d4 Nf6 3. Nc3)  (1... b6  2. d4 Bb7 3. Nd2)  (1... Nc6  2. d4 d5 3. e5 Bf5 4. c3 e6 5. Ne2 Be7 6. Ng3 Bg6 7. Be2 f6 8. f4 Nh6 9. O-O)  (1... Nf6  2. e5) 2. Nf3 d6  (2... Nc6  3. Bb5 a6  (3... d6  4. Bxc6+ bxc6 5. O-O g6 6. d4) 4. Bxc6)  (2... e6  3. c3) 3. Bb5+ Bd7  (3... Nc6  4. Bxc6+ bxc6 5. O-O g6 6. d4) 4. Bxd7+ Nxd7 5. O-O *

### Platform and versions

Windows 10
En Croissant Version: 0.11.1

### Stack trace

The only thing abnormal I see in the EC logs is the following:

[2024-09-07][21:17:05][WARN][tao::platform_impl::platform::event_loop::runner] NewEvents emitted without explicit RedrawEventsCleared
[2024-09-07][21:17:05][WARN][tao::platform_impl::platform::event_loop::runner] RedrawEventsCleared emitted without explicit MainEventsCleared

**Comment by franciscoBSalgueiro** [comment]
I tried your reproduction and it continued the training for me.

**Comment by franciscoBSalgueiro** [comment]
I've changed it so that only the first transposition is considered. In the future it would be good to make it easier to detect transpositions
