### ISSUE TITLE
A way of accessing the engine logs (this could be in the sidebar with "Engines" and "Report")

### ISSUE THREAD

**Issue by franciscoBSalgueiro** [franciscoBSalgueiro/en-croissant#45]

**Comment by dav1312** [comment]
Actually since multiple engines can be enabled at the same time, maybe its easier to just add another dropdown like the quick settings button

**Comment by franciscoBSalgueiro** [comment]
I feel like that might make the interface too cluttered. I liked the idea of putting it on a new section on the sidebar
