### ISSUE TITLE
Cant flip the board

### ISSUE THREAD

**Issue by Teals53** [franciscoBSalgueiro/en-croissant#457]
### Describe the bug

title says all

### Reproduction

make black engine and white human and try to flip board it wont working

### Platform and versions

latest

**Comment by the-juju** [comment]
I'm not able to reproduce on my side. Woul you like to give more details that can lead to a reproduction?

**Comment by Teals53** [comment]
> I'm not able to reproduce on my side. Woul you like to give more details that can lead to a reproduction?

r u related to software?

**Comment by the-juju** [comment]
I'm just offering to help. And as I'm not able to reproduce your issue i'm trying to investigate in order to solve your issue.

**Comment by franciscoBSalgueiro** [comment]
This was already fixed in the master branch

**Comment by Teals53** [comment]
> This was already fixed in the master branch

like we had to wait for release?
