### ISSUE TITLE
Shouldn't be possible to keep downloading user games once it reaches 100%

### ISSUE THREAD

**Issue by franciscoBSalgueiro** [franciscoBSalgueiro/en-croissant#54]
This should be fixed by https://github.com/franciscoBSalgueiro/en-croissant/commit/bf0ddfb8d904450f24492e668456270dfefb8145

**Comment by dav1312** [comment]
I tried to download magnus' games and I got this

![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/63931154/4de850ab-f26e-45f7-a9fe-475cf0bea0c5)

**Comment by franciscoBSalgueiro** [comment]
It seems to be an issue with the games count provided by the chess.com API, which isn't consistent with the actual number of games available to download.
