### ISSUE TITLE
Feature suggestion: Eval chart for game report

### ISSUE THREAD

**Issue by sleeplessghost** [franciscoBSalgueiro/en-croissant#57]
It would be nice to have an eval chart shown after generating a report of a game similar to what lichess shows:

![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/25903992/53480453-a3b8-47d9-9794-d6ff1bf19338)

May need some reworking of the Report panel as there doesn't look to be much space for it currently, perhaps the section with accuracy / acpl / number of good etc moves could be compacted? Or the chart could go in another panel potentially.

Lichess uses a `highcharts` area chart, should hopefully also be possible to make something similar with `recharts` area chart https://recharts.org/en-US/api/AreaChart

I'm happy to add this, just wanted to check if it was a feature you wanted first and if you have any thoughts about where it should go in the UI

Sidenotes:
- Could potentially hide the "Generate report" button after you have generated a report (unless the PGN is modified)
- The "Generate report" modal could default to selecting the first engine (if you have any) instead of requiring it to be picked each time

**Comment by dav1312** [comment]
_Note that I already had this as a suggestion in my issue https://github.com/franciscoBSalgueiro/en-croissant/issues/11_

It would be even better to always have access to the chart, not just for reports

**Comment by franciscoBSalgueiro** [comment]
I think just putting everything inside a scroll area in the Report tab would be enough to make space for this.

> 
> It would be even better to always have access to the chart, not just for reports

Currently the way the report works is by analyzing every position sequentially, but if you just analyze every position manually it will still give you the same report.

We could also have an eval graph for a game where not every position has been analyzed and make it look like the eval graph in lichess while the report is processing (only some parts of the graph are shown).
