### ISSUE TITLE
Bug when trying to add account

### ISSUE THREAD

**Issue by PaulJeFi** [franciscoBSalgueiro/en-croissant#6]
I tried on MacOS to add my chess.com account. Then this error occurs :
```Application error: a client-side exception has occurred (see the browser console for more information).```
Of course, the Home menu is not working anymore, always showing this message when I try to open it. I tried to delete the app and install it again, but the same message appears. I think a file was written in my system and the new installed app uses this file …

**Comment by franciscoBSalgueiro** [comment]
Thanks for the report! I've added more error checks on the home page for the next release, so it should give an error message instead of the whole page crashing.
