### ISSUE TITLE
Opening a game from my opening repertoire PGN shows only 1 variation when many are present

### ISSUE THREAD

**Issue by alex-k03** [franciscoBSalgueiro/en-croissant#60]
I'm using en croissant on MacOS 13 Ventura. When I import my opening repertoire in PGN format, each opening is stored as one game with many variations. En croissant says each of these games have only 1 variation, the main line. The issue is not in the PGN file as opening it in Stockfish for Mac or ChessX shows the variations correctly.

**Comment by alex-k03** [comment]
Here is an example game with many variations where en croissant only shows the main line

This is what is contained in the PGN file:
[Event "Black repertoire"]
[Site "Chesstempo.com opening repertoire"]
[Date "2023.10.28"]
[Round "?"]
[White "?"]
[Black "Marshall"]
[Result "*"]
[ChesstempoRepertoireColour "Black"]

1.e4 e5 2.Nf3 Nc6 3.Bb5 a6 4.Ba4 Nf6 5.O-O Be7 6.Re1 b5 7.Bb3 O-O 8.c3 d5 9.exd5 Nxd5 10.Nxe5 Nxe5 11.Rxe5 c6 12.d4 ( 12.d3 Bd6 13.Re1 Bf5 14.Qf3 Re8 15.Rxe8+ Qxe8 16.Nd2 Qe1+ 17.Nf1 Bg6 18.Bc2 Nxc3 19.bxc3 Qxc3 ) 12...Bd6 13.Re1 Qh4 14.g3 Qh3 15.Re4 ( 15.Be3 Ra7 16.Nd2 ( 16.Qf3 ) 16...Bg4 17.Qc2 Bf5 18.Qc1 Re7 19.Bg5 Rxe1+ 20.Qxe1 h6 21.Be3 Bd3 22.Qd1 ( 22.Nf1 Be4 ) 22...Nxe3 23.fxe3 Bxg3 24.hxg3 Qxg3+ 25.Kh1 Qh3+ 26.Kg1 Qxe3+ ) 15...g5 16.Qf3 ( 16.Qe1 f5 17.Re8 ( 17.Re6 Bxe6 18.Qxe6+ Kh8 19.Qxd6 Rae8 20.Bd2 f4 ) ( 17.Bxd5+ cxd5 18.Re6 Bxe6 19.Qxe6+ Kg7 20.Qxd6 ( 20.Bxg5 Qh5 ) 20...f4 ) 17...f4 18.Nd2 Bg4 ) ( 16.Qf1 Qh6 17.Re1 Nf4 18.gxf4 gxf4 ) ( 16.Bxg5 ) 16...Bf5 17.Bc2 ( 17.Bxd5 cxd5 18.Re3 Rad8 19.Nd2 Rfe8 20.a4 b4 21.c4 dxc4 22.Nxc4 Bd3 ) 17...Bxe4 18.Bxe4 Qe6 19.Bxg5 f5 20.Bd3 f4 21.Qe4 Qd7 22.Nd2 Rae8 23.Qh1 Qg7 *

This is what is shown in en croissant:
[Event "Black repertoire"]
[Site "Chesstempo.com opening repertoire"]
[Date "2023.10.28"]
[Round "?"]
[White "?"]
[Black "Marshall"]
[Result "*"]
[Orientation "black"]

1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O Be7 6. Re1 b5 7. Bb3 O-O 8. c3 d5 9. exd5 Nxd5 10. Nxe5 Nxe5 11. Rxe5 c6 12. d4 Bd6 13. Re1 Qh4 14. g3 Qh3 15. Re4 g5 16. Qf3 Bf5 17. Bc2 Bxe4 18. Bxe4 Qe6 19. Bxg5 f5 20. Bd3 f4 21. Qe4 Qd7 22. Nd2 Rae8 23. Qh1 Qg7

**Comment by dav1312** [comment]
I cannot reproduce
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/63931154/fe18c7cf-79cd-4ed3-a497-ef53eb67a774)

**Comment by alex-k03** [comment]
@dav1312 how did you open the game?

**Comment by dav1312** [comment]
> @dav1312 how did you open the game?

I tried both loading from a file and copy pasting it

**Comment by alex-k03** [comment]
ah, I see it also works when I load from a file, but not when I import the openings PGN as a Database and attempt to open games from there - I suppose maybe databases can only contain games without variations?

**Comment by alex-k03** [comment]
Also when managing the repertoire from a file instead of a database, there doesn't seem to be an option in the info tab to name the white and black players in new games. The rest of my games are labelled 'Name of opening' vs '?', but the new games cannot be named.

**Comment by franciscoBSalgueiro** [comment]
Yes that's correct, when converting to a database, only the mainline will be stored.
