### ISSUE TITLE
Incorrect accuracy displayed

### ISSUE THREAD

**Issue by nobnap** [franciscoBSalgueiro/en-croissant#7]
The post-game report displayed the bot's accuracy as 113.6%
![Screenshot 2023-05-12 164041](https://github.com/franciscoBSalgueiro/en-croissant/assets/100365639/326ddd34-72e6-4de9-ab10-a6228292bb3d)

**Comment by franciscoBSalgueiro** [comment]
Thanks, the average accuracy and centipawn loss calculations should be fixed  in 0.3.1.
