### ISSUE TITLE
Unable to open application

### ISSUE THREAD

**Issue by Mauritz8** [franciscoBSalgueiro/en-croissant#76]
The steps I followed were the following: 
1. I downloaded the linux .deb file from the website, as I am running Ubuntu 22.04.3 LTS.
2. sudo apt install ./en-croissant_0.6.0_amd64.deb 
3. I then executed the binary, and this is the output that I get
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/67279312/d3d3958c-0a04-4a6f-99c2-99d264470935)

I don't know what the issue is, but I've been trying to fix this for the last couple of hours without much success, so any help I could get would be appreciated.

**Comment by franciscoBSalgueiro** [comment]
Are you using Nvidia?

Maybe try `WEBKIT_DISABLE_COMPOSITING_MODE=1 en-croissant`

**Comment by Mauritz8** [comment]
Yes I'm using Nvidia, and your solution works! For now I can export this environmental variable in my .bashrc and everything works without issues, but do you perhaps know what the underlying issue is with my Nvidia GPU? I seem to have a correct and up-to-date driver. Anyways I just wanted to say that I've been really eager to try en-croissant since it looks astonishing, and no other chess GUI's I've seen are even close to it in comparison (in my opinion). I can't thank you enough, both for developing this app, and for fixing my problem.

**Comment by franciscoBSalgueiro** [comment]
Thanks for the kind words!

It's a bug with webkitgtk, but a [new release](https://webkitgtk.org/2023/11/10/webkitgtk2.42.2-released.html) came out today that fixes it, so once you're able to upgrade, the flag should no longer be necessary.
