### ISSUE TITLE
Move tags (mistake, brilliant...) in the chessboard

### ISSUE THREAD

**Issue by franciscoBSalgueiro** [franciscoBSalgueiro/en-croissant#78]

**Comment by dav1312** [comment]
If possible I think it would be cool to also change the color of the last move

![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/63931154/8ca92d1f-8395-4d5f-ab80-cbcd20befbbf)
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/63931154/8b2ed7a2-72a9-445a-a175-2dee1ddb10e0)
