### ISSUE TITLE
Downloaded games percentage is over 100%

### ISSUE THREAD

**Issue by Sgridev** [franciscoBSalgueiro/en-croissant#97]
Downloaded games percentage is over 100%
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/35015674/f7978e9a-8630-4526-98a3-5de55d6cd7bb)

**Comment by dav1312** [comment]
Duplicate of https://github.com/franciscoBSalgueiro/en-croissant/issues/84

**Comment by franciscoBSalgueiro** [comment]
Also see https://github.com/franciscoBSalgueiro/en-croissant/pull/85#issuecomment-1806865554 as to why it's currently not fixable.
